"""
viseda.report.html_report
-------------------------
Generates a self-contained HTML EDA report from a summary dict.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any, Dict


_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8"/>
<meta name="viewport" content="width=device-width, initial-scale=1.0"/>
<title>{title}</title>
<style>
  :root {{
    --bg: #0d1117; --surface: #161b22; --border: #30363d;
    --text: #e6edf3; --muted: #8b949e; --accent: #58a6ff;
    --green: #3fb950; --red: #f78166; --yellow: #e3b341;
  }}
  * {{ box-sizing: border-box; margin: 0; padding: 0; }}
  body {{ background: var(--bg); color: var(--text);
         font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
         padding: 2rem; }}
  h1 {{ font-size: 1.8rem; margin-bottom: 0.25rem; }}
  h2 {{ font-size: 1.1rem; color: var(--accent); margin: 1.5rem 0 0.5rem; }}
  h3 {{ font-size: 0.9rem; color: var(--muted); margin: 1rem 0 0.3rem; }}
  .subtitle {{ color: var(--muted); margin-bottom: 2rem; font-size: 0.9rem; }}
  .grid {{ display: grid; grid-template-columns: repeat(auto-fill, minmax(260px, 1fr));
           gap: 1rem; }}
  .card {{ background: var(--surface); border: 1px solid var(--border);
           border-radius: 8px; padding: 1rem; }}
  .card h3 {{ font-size: 0.8rem; color: var(--muted); margin-bottom: 0.5rem;
              text-transform: uppercase; letter-spacing: 0.05em; }}
  .stat {{ display: flex; justify-content: space-between; font-size: 0.85rem;
           padding: 0.2rem 0; border-bottom: 1px solid var(--border); }}
  .stat:last-child {{ border-bottom: none; }}
  .val {{ font-variant-numeric: tabular-nums; color: var(--accent); }}
  .badge {{ display: inline-block; padding: 0.15rem 0.5rem; border-radius: 12px;
            font-size: 0.75rem; font-weight: 600; margin: 0.15rem; }}
  .badge-blue {{ background: rgba(88,166,255,0.15); color: var(--accent); }}
  .badge-green {{ background: rgba(63,185,80,0.15); color: var(--green); }}
  .badge-red {{ background: rgba(247,129,102,0.15); color: var(--red); }}
  .badge-yellow {{ background: rgba(227,179,65,0.15); color: var(--yellow); }}
  .bar-wrap {{ margin-top: 0.5rem; }}
  .bar-row {{ display: flex; align-items: center; gap: 0.5rem; margin: 0.2rem 0; font-size: 0.78rem; }}
  .bar-label {{ width: 110px; white-space: nowrap; overflow: hidden; text-overflow: ellipsis; color: var(--muted); }}
  .bar {{ flex: 1; background: var(--border); border-radius: 4px; height: 10px; }}
  .bar-fill {{ height: 100%; border-radius: 4px; background: var(--accent); }}
  .bar-count {{ width: 60px; text-align: right; color: var(--accent); }}
  .corrupt {{ color: var(--red); font-size: 0.8rem; margin-top: 0.5rem;
              max-height: 200px; overflow-y: auto; }}
  footer {{ margin-top: 3rem; color: var(--muted); font-size: 0.75rem;
            border-top: 1px solid var(--border); padding-top: 1rem; }}
</style>
</head>
<body>
<h1>🔬 {title}</h1>
<p class="subtitle">Generated by <strong>VisEDA</strong></p>

{body}

<footer>Generated by VisEDA &mdash; Visual Exploratory Data Analysis</footer>
</body>
</html>
"""


def _stat_card(title: str, stats: Dict) -> str:
    if not stats:
        return ""
    rows = "".join(
        f'<div class="stat"><span>{k}</span>'
        f'<span class="val">{_fmt(v)}</span></div>'
        for k, v in stats.items()
    )
    return f'<div class="card"><h3>{title}</h3>{rows}</div>'


def _fmt(v) -> str:
    if isinstance(v, float):
        return f"{v:,.3f}"
    if isinstance(v, int):
        return f"{v:,}"
    return str(v)


def _bar_chart(title: str, dist: Dict, color_class: str = "badge-blue") -> str:
    if not dist:
        return ""
    total = sum(dist.values()) or 1
    max_val = max(dist.values()) or 1
    bars = ""
    for label, count in sorted(dist.items(), key=lambda x: -x[1])[:30]:
        pct = count / max_val * 100
        bars += (
            f'<div class="bar-row">'
            f'<span class="bar-label" title="{label}">{label}</span>'
            f'<div class="bar"><div class="bar-fill" style="width:{pct:.1f}%"></div></div>'
            f'<span class="bar-count">{count:,}</span>'
            f"</div>"
        )
    return f'<div class="card" style="grid-column: span 2;"><h3>{title}</h3><div class="bar-wrap">{bars}</div></div>'


def generate_html_report(
    summary: Dict[str, Any],
    output_path: str,
    title: str = "VisEDA Report",
) -> None:
    sections = []

    # ── Overview badges ──────────────────────────────────────────────
    badges = ""
    if "total_images" in summary:
        badges += f'<span class="badge badge-blue">{summary["total_images"]:,} images</span>'
    if "valid_images" in summary:
        badges += f'<span class="badge badge-green">{summary["valid_images"]:,} valid</span>'
    if summary.get("corrupt_images"):
        badges += f'<span class="badge badge-red">{summary["corrupt_images"]:,} corrupt</span>'
    if "n_points" in summary:
        badges += f'<span class="badge badge-blue">{summary["n_points"]:,} points</span>'
    if summary.get("n_duplicate_groups"):
        badges += (
            f'<span class="badge badge-yellow">'
            f'{summary["n_duplicate_groups"]:,} duplicate groups</span>'
        )

    if badges:
        sections.append(f"<h2>Overview</h2><p>{badges}</p>")

    # ── Grid of stat cards ───────────────────────────────────────────
    stat_keys = [
        "height", "width", "aspect_ratio", "file_size_kb",
        "brightness", "contrast", "sharpness",
        "x", "y", "z",
        "intensity",
    ]
    cards = ""
    for key in stat_keys:
        if key in summary and summary[key]:
            cards += _stat_card(key.replace("_", " ").title(), summary[key])

    if "bounding_box" in summary:
        bb = summary["bounding_box"]
        cards += _stat_card("Bounding Box", {
            "X extent": bb["extent"][0],
            "Y extent": bb["extent"][1],
            "Z extent": bb["extent"][2],
            "Volume": summary.get("volume_bounding_box", 0),
            "Density (pts/unit³)": summary.get("density_pts_per_unit3", 0),
        })

    if cards:
        sections.append(f'<h2>Statistics</h2><div class="grid">{cards}</div>')

    # ── Channel / RGB ─────────────────────────────────────────────────
    if "mean_pixel_per_channel" in summary and summary["mean_pixel_per_channel"]:
        ch_stats = {}
        for i, (mn, st) in enumerate(zip(
            summary["mean_pixel_per_channel"],
            summary.get("std_pixel_per_channel", [0] * 3),
        )):
            ch_stats[f"Channel {i} mean"] = mn
            ch_stats[f"Channel {i} std"] = st
        cards2 = _stat_card("Channel Statistics", ch_stats)
        sections.append(f'<h2>Pixel Statistics</h2><div class="grid">{cards2}</div>')

    # ── Label distribution ────────────────────────────────────────────
    if summary.get("label_distribution"):
        sections.append(
            f'<h2>Label Distribution</h2>'
            f'<div class="grid">'
            f'{_bar_chart("Labels", summary["label_distribution"])}'
            f'</div>'
        )

    # ── Channel distribution ──────────────────────────────────────────
    if summary.get("channel_distribution"):
        sections.append(
            f'<div class="grid">'
            f'{_bar_chart("Channel Distribution", {str(k)+"-ch": v for k, v in summary["channel_distribution"].items()})}'
            f'</div>'
        )

    # ── Corrupt files ─────────────────────────────────────────────────
    if summary.get("corrupt_paths"):
        items = "".join(f"<li>{p}</li>" for p in summary["corrupt_paths"][:50])
        sections.append(
            f'<h2>Corrupt Files ({len(summary["corrupt_paths"])})</h2>'
            f'<div class="corrupt"><ul>{items}</ul></div>'
        )

    # ── Duplicate groups ──────────────────────────────────────────────
    if summary.get("duplicate_groups"):
        groups_html = ""
        for grp in summary["duplicate_groups"][:10]:
            items = "".join(f"<li>{p}</li>" for p in grp)
            groups_html += f"<ul>{items}</ul><hr/>"
        sections.append(
            f'<h2>Duplicate Groups (showing first 10)</h2>'
            f'<div class="card">{groups_html}</div>'
        )

    body = "\n".join(sections)
    html = _TEMPLATE.format(title=title, body=body)

    Path(output_path).write_text(html, encoding="utf-8")